import {
  ArbitrageOpportunity,
  ExchangeInfo,
  TriangularOpportunity,
  DexOpportunity,
  FundingOpportunity,
  PaperTrade,
  AlertRule,
  ApiCredential,
  UserProfile,
  ActiveSession,
  NotificationItem,
  OrderBook,
} from './types';

export const MOCK_EXCHANGES: ExchangeInfo[] = [
  { id: 'binance', name: 'Binance', makerFee: 0.1, takerFee: 0.1, withdrawalFees: { BTC: 0.0002, ETH: 0.001, USDT: 1.0 }, status: 'Operational', latencyMs: 38, apiConnected: true },
  { id: 'coinbase', name: 'Coinbase Advanced', makerFee: 0.4, takerFee: 0.6, withdrawalFees: { BTC: 0.0001, ETH: 0.0008, USDT: 2.5 }, status: 'Operational', latencyMs: 52, apiConnected: true },
  { id: 'kraken', name: 'Kraken Pro', makerFee: 0.16, takerFee: 0.26, withdrawalFees: { BTC: 0.0002, ETH: 0.001, USDT: 1.5 }, status: 'Operational', latencyMs: 44, apiConnected: false },
  { id: 'okx', name: 'OKX', makerFee: 0.08, takerFee: 0.1, withdrawalFees: { BTC: 0.00015, ETH: 0.0008, USDT: 1.0 }, status: 'Operational', latencyMs: 41, apiConnected: false },
  { id: 'bybit', name: 'Bybit', makerFee: 0.1, takerFee: 0.1, withdrawalFees: { BTC: 0.0002, ETH: 0.001, USDT: 1.0 }, status: 'Operational', latencyMs: 40, apiConnected: true },
  { id: 'kucoin', name: 'KuCoin', makerFee: 0.1, takerFee: 0.1, withdrawalFees: { BTC: 0.0002, ETH: 0.0012, USDT: 1.2 }, status: 'Operational', latencyMs: 65, apiConnected: false },
  { id: 'gateio', name: 'Gate.io', makerFee: 0.15, takerFee: 0.2, withdrawalFees: { BTC: 0.0003, ETH: 0.0015, USDT: 1.5 }, status: 'Operational', latencyMs: 82, apiConnected: false },
  { id: 'bitfinex', name: 'Bitfinex', makerFee: 0.1, takerFee: 0.2, withdrawalFees: { BTC: 0.0004, ETH: 0.0012, USDT: 2.0 }, status: 'Operational', latencyMs: 70, apiConnected: false },
  { id: 'coindcx', name: 'CoinDCX', makerFee: 0.2, takerFee: 0.2, withdrawalFees: { BTC: 0.0002, ETH: 0.001, USDT: 2.0 }, status: 'Operational', latencyMs: 95, apiConnected: false },
  { id: 'wazirx', name: 'WazirX', makerFee: 0.2, takerFee: 0.2, withdrawalFees: { BTC: 0.00025, ETH: 0.0015, USDT: 2.5 }, status: 'Operational', latencyMs: 110, apiConnected: false },
];

export const MOCK_OPPORTUNITIES: ArbitrageOpportunity[] = [
  {
    id: 'opp-1',
    asset: 'BTC',
    pair: 'BTC/USDT',
    buyExchange: 'Kraken Pro',
    sellExchange: 'Binance',
    buyPrice: 94120.50,
    sellPrice: 95210.00,
    grossSpread: 1089.50,
    grossSpreadPct: 1.15,
    buyFeePct: 0.16,
    sellFeePct: 0.10,
    estimatedSlippagePct: 0.04,
    networkCostUSD: 12.50,
    otherCostsUSD: 5.00,
    estimatedNetProfitUSD: 785.40,
    estimatedNetRoiPct: 0.83,
    liquidityUSD: 450000,
    orderBookDepthBuy: 4.8,
    orderBookDepthSell: 6.2,
    dataAgeSeconds: 0.3,
    riskLevel: 'Low',
    opportunityScore: 91,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-2',
    asset: 'ETH',
    pair: 'ETH/USDT',
    buyExchange: 'OKX',
    sellExchange: 'Coinbase Advanced',
    buyPrice: 2680.10,
    sellPrice: 2728.50,
    grossSpread: 48.40,
    grossSpreadPct: 1.80,
    buyFeePct: 0.08,
    sellFeePct: 0.40,
    estimatedSlippagePct: 0.06,
    networkCostUSD: 4.20,
    otherCostsUSD: 2.00,
    estimatedNetProfitUSD: 312.80,
    estimatedNetRoiPct: 1.16,
    liquidityUSD: 280000,
    orderBookDepthBuy: 38.5,
    orderBookDepthSell: 45.1,
    dataAgeSeconds: 0.5,
    riskLevel: 'Low',
    opportunityScore: 88,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-3',
    asset: 'SOL',
    pair: 'SOL/USDT',
    buyExchange: 'Bybit',
    sellExchange: 'Gate.io',
    buyPrice: 182.40,
    sellPrice: 187.90,
    grossSpread: 5.50,
    grossSpreadPct: 3.01,
    buyFeePct: 0.10,
    sellFeePct: 0.20,
    estimatedSlippagePct: 0.12,
    networkCostUSD: 0.80,
    otherCostsUSD: 1.00,
    estimatedNetProfitUSD: 462.10,
    estimatedNetRoiPct: 2.53,
    liquidityUSD: 150000,
    orderBookDepthBuy: 820,
    orderBookDepthSell: 940,
    dataAgeSeconds: 0.4,
    riskLevel: 'Medium',
    opportunityScore: 84,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-4',
    asset: 'XRP',
    pair: 'XRP/USDT',
    buyExchange: 'KuCoin',
    sellExchange: 'Bitfinex',
    buyPrice: 2.38,
    sellPrice: 2.45,
    grossSpread: 0.07,
    grossSpreadPct: 2.94,
    buyFeePct: 0.10,
    sellFeePct: 0.20,
    estimatedSlippagePct: 0.15,
    networkCostUSD: 0.50,
    otherCostsUSD: 0.50,
    estimatedNetProfitUSD: 248.00,
    estimatedNetRoiPct: 2.39,
    liquidityUSD: 95000,
    orderBookDepthBuy: 42000,
    orderBookDepthSell: 38000,
    dataAgeSeconds: 0.8,
    riskLevel: 'Medium',
    opportunityScore: 79,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-5',
    asset: 'DOGE',
    pair: 'DOGE/USDT',
    buyExchange: 'CoinDCX',
    sellExchange: 'Binance',
    buyPrice: 0.245,
    sellPrice: 0.254,
    grossSpread: 0.009,
    grossSpreadPct: 3.67,
    buyFeePct: 0.20,
    sellFeePct: 0.10,
    estimatedSlippagePct: 0.25,
    networkCostUSD: 1.00,
    otherCostsUSD: 1.00,
    estimatedNetProfitUSD: 312.00,
    estimatedNetRoiPct: 3.12,
    liquidityUSD: 60000,
    orderBookDepthBuy: 240000,
    orderBookDepthSell: 280000,
    dataAgeSeconds: 1.1,
    riskLevel: 'High',
    opportunityScore: 72,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-6',
    asset: 'ADA',
    pair: 'ADA/USDT',
    buyExchange: 'Binance',
    sellExchange: 'WazirX',
    buyPrice: 0.820,
    sellPrice: 0.858,
    grossSpread: 0.038,
    grossSpreadPct: 4.63,
    buyFeePct: 0.10,
    sellFeePct: 0.20,
    estimatedSlippagePct: 0.30,
    networkCostUSD: 1.50,
    otherCostsUSD: 1.00,
    estimatedNetProfitUSD: 403.00,
    estimatedNetRoiPct: 4.03,
    liquidityUSD: 45000,
    orderBookDepthBuy: 55000,
    orderBookDepthSell: 48000,
    dataAgeSeconds: 0.6,
    riskLevel: 'High',
    opportunityScore: 68,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-7',
    asset: 'AVAX',
    pair: 'AVAX/USDT',
    buyExchange: 'OKX',
    sellExchange: 'Coinbase Advanced',
    buyPrice: 28.50,
    sellPrice: 29.25,
    grossSpread: 0.75,
    grossSpreadPct: 2.63,
    buyFeePct: 0.08,
    sellFeePct: 0.40,
    estimatedSlippagePct: 0.10,
    networkCostUSD: 0.50,
    otherCostsUSD: 0.50,
    estimatedNetProfitUSD: 205.00,
    estimatedNetRoiPct: 2.05,
    liquidityUSD: 120000,
    orderBookDepthBuy: 4200,
    orderBookDepthSell: 5100,
    dataAgeSeconds: 0.4,
    riskLevel: 'Low',
    opportunityScore: 86,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-8',
    asset: 'LINK',
    pair: 'LINK/USDT',
    buyExchange: 'Bybit',
    sellExchange: 'Kraken Pro',
    buyPrice: 18.10,
    sellPrice: 18.62,
    grossSpread: 0.52,
    grossSpreadPct: 2.87,
    buyFeePct: 0.10,
    sellFeePct: 0.16,
    estimatedSlippagePct: 0.08,
    networkCostUSD: 2.00,
    otherCostsUSD: 1.00,
    estimatedNetProfitUSD: 253.00,
    estimatedNetRoiPct: 2.53,
    liquidityUSD: 180000,
    orderBookDepthBuy: 9800,
    orderBookDepthSell: 11200,
    dataAgeSeconds: 0.3,
    riskLevel: 'Low',
    opportunityScore: 89,
    isLive: true,
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_TRIANGULAR: TriangularOpportunity[] = [
  {
    id: 'tri-1',
    baseAsset: 'USDT',
    leg1Pair: 'USDT -> BTC',
    leg1Exchange: 'Binance',
    leg1Price: 95000.00,
    leg2Pair: 'BTC -> ETH',
    leg2Exchange: 'Binance',
    leg2Price: 35.15, // 1 BTC = 35.15 ETH
    leg3Pair: 'ETH -> USDT',
    leg3Exchange: 'Binance',
    leg3Price: 2720.00,
    startingAmountUSD: 10000,
    finalAmountUSD: 10118.50,
    grossSpreadPct: 1.45,
    totalFeesUSD: 26.50,
    estimatedNetProfitUSD: 92.00,
    netRoiPct: 0.92,
    riskLevel: 'Low',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tri-2',
    baseAsset: 'USDT',
    leg1Pair: 'USDT -> SOL',
    leg1Exchange: 'Bybit',
    leg1Price: 183.00,
    leg2Pair: 'SOL -> ETH',
    leg2Exchange: 'Bybit',
    leg2Price: 0.068,
    leg3Pair: 'ETH -> USDT',
    leg3Exchange: 'Bybit',
    leg3Price: 2735.00,
    startingAmountUSD: 10000,
    finalAmountUSD: 10204.00,
    grossSpreadPct: 2.04,
    totalFeesUSD: 30.00,
    estimatedNetProfitUSD: 174.00,
    netRoiPct: 1.74,
    riskLevel: 'Medium',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_DEX: DexOpportunity[] = [
  {
    id: 'dex-1',
    token: 'ETH',
    network: 'Ethereum',
    buyDex: 'Uniswap v3',
    sellDex: 'Sushiswap',
    buyPrice: 2690.00,
    sellPrice: 2732.00,
    grossSpreadPct: 1.56,
    gasCostUSD: 12.80,
    priceImpactPct: 0.15,
    liquidityUSD: 1200000,
    estimatedNetProfitUSD: 112.50,
    netRoiPct: 1.12,
    riskLevel: 'Low',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dex-2',
    token: 'SOL',
    network: 'Solana',
    buyDex: 'Raydium',
    sellDex: 'Orca',
    buyPrice: 182.10,
    sellPrice: 186.80,
    grossSpreadPct: 2.58,
    gasCostUSD: 0.05,
    priceImpactPct: 0.22,
    liquidityUSD: 850000,
    estimatedNetProfitUSD: 231.00,
    netRoiPct: 2.31,
    riskLevel: 'Low',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_FUNDING: FundingOpportunity[] = [
  {
    id: 'fund-1',
    asset: 'BTC',
    exchange: 'Binance Perpetual',
    spotPrice: 94800.00,
    futuresPrice: 95350.00,
    fundingRate8hPct: 0.045, // 0.045% per 8h
    annualizedYieldPct: 49.27,
    basisUSD: 550.00,
    estimatedNetProfitUSD: 410.00,
    riskLevel: 'Low',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fund-2',
    asset: 'ETH',
    exchange: 'Bybit Futures',
    spotPrice: 2690.00,
    futuresPrice: 2718.00,
    fundingRate8hPct: 0.062,
    annualizedYieldPct: 67.89,
    basisUSD: 28.00,
    estimatedNetProfitUSD: 520.00,
    riskLevel: 'Low',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_PAPER_TRADES: PaperTrade[] = [
  {
    id: 'pt-101',
    opportunityId: 'opp-1',
    asset: 'BTC/USDT',
    buyExchange: 'Kraken Pro',
    sellExchange: 'Binance',
    buyPrice: 94120.50,
    sellPrice: 95210.00,
    capitalUSD: 10000,
    feesPaidUSD: 26.00,
    slippageIncurredUSD: 4.00,
    netProfitUSD: 85.80,
    roiPct: 0.86,
    status: 'Completed',
    executionTimeMs: 420,
    mode: 'Paper',
    executedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'pt-102',
    opportunityId: 'opp-2',
    asset: 'ETH/USDT',
    buyExchange: 'OKX',
    sellExchange: 'Coinbase Advanced',
    buyPrice: 2680.10,
    sellPrice: 2728.50,
    capitalUSD: 5000,
    feesPaidUSD: 24.00,
    slippageIncurredUSD: 3.00,
    netProfitUSD: 63.10,
    roiPct: 1.26,
    status: 'Completed',
    executionTimeMs: 380,
    mode: 'Paper',
    executedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'pt-103',
    opportunityId: 'opp-3',
    asset: 'SOL/USDT',
    buyExchange: 'Bybit',
    sellExchange: 'Gate.io',
    buyPrice: 182.40,
    sellPrice: 187.90,
    capitalUSD: 2500,
    feesPaidUSD: 7.50,
    slippageIncurredUSD: 3.00,
    netProfitUSD: 64.80,
    roiPct: 2.59,
    status: 'Completed',
    executionTimeMs: 510,
    mode: 'Paper',
    executedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const MOCK_ALERTS: AlertRule[] = [
  {
    id: 'alt-1',
    asset: 'BTC',
    exchange: 'All',
    minGrossSpreadPct: 1.0,
    minNetRoiPct: 0.5,
    minNetProfitUSD: 50,
    minLiquidityUSD: 100000,
    maxSlippagePct: 0.1,
    channel: 'In-App',
    frequency: 'Immediate',
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'alt-2',
    asset: 'SOL',
    exchange: 'Bybit',
    minGrossSpreadPct: 2.0,
    minNetRoiPct: 1.5,
    minNetProfitUSD: 100,
    minLiquidityUSD: 50000,
    maxSlippagePct: 0.2,
    channel: 'Email',
    frequency: 'Immediate',
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

export const MOCK_API_CREDENTIALS: ApiCredential[] = [
  {
    id: 'api-1',
    exchangeId: 'binance',
    exchangeName: 'Binance',
    apiKeyMasked: 'vmPU...8kL9',
    permissions: { read: true, trade: true, withdraw: false },
    status: 'Connected',
    lastTestedAt: new Date().toISOString(),
    latencyMs: 38,
  },
  {
    id: 'api-2',
    exchangeId: 'coinbase',
    exchangeName: 'Coinbase Advanced',
    apiKeyMasked: 'organizations/.../apiKeys/9a7c...',
    permissions: { read: true, trade: true, withdraw: false },
    status: 'Connected',
    lastTestedAt: new Date().toISOString(),
    latencyMs: 52,
  },
  {
    id: 'api-3',
    exchangeId: 'bybit',
    exchangeName: 'Bybit',
    apiKeyMasked: '39aB...21qW',
    permissions: { read: true, trade: true, withdraw: false },
    status: 'Connected',
    lastTestedAt: new Date().toISOString(),
    latencyMs: 40,
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-90210',
  fullName: 'Alexander Vance',
  username: 'alexvance',
  email: 'alex.vance@fintech-ag.io',
  mobile: '+1 (555) 234-5678',
  country: 'United States',
  createdAt: '2025-11-14',
  verificationStatus: 'Verified',
  plan: 'Pro',
  mfaEnabled: true,
  paperBalanceUSD: 100000,
};

export const MOCK_SESSIONS: ActiveSession[] = [
  {
    id: 'sess-1',
    device: 'MacBook Pro 16"',
    browser: 'Chrome 128.0',
    ip: '192.168.1.42 (US East)',
    location: 'New York, USA',
    isCurrent: true,
    lastActive: 'Just now',
  },
  {
    id: 'sess-2',
    device: 'iPhone 15 Pro',
    browser: 'Safari Mobile',
    ip: '72.14.192.1 (US Mobile)',
    location: 'New York, USA',
    isCurrent: false,
    lastActive: '2 hours ago',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'High Yield BTC Spread Detected',
    message: 'Kraken -> Binance spread widened to 1.15% (Net ROI 0.83%).',
    type: 'opportunity',
    timestamp: '2 mins ago',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Paper Trade Executed',
    message: 'Simulated $10,000 BTC order completed with +$85.80 net P/L.',
    type: 'trade',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'API Status Normal',
    message: 'Binance and Coinbase endpoints responding with <50ms latency.',
    type: 'system',
    timestamp: '5 hours ago',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'Security Alert',
    message: 'New login session authenticated from Chrome Mac OS.',
    type: 'security',
    timestamp: '1 day ago',
    read: true,
  },
];

export function getMockOrderBook(pair: string): { buyBook: OrderBook; sellBook: OrderBook } {
  const basePrice = pair.startsWith('BTC') ? 95000 : pair.startsWith('ETH') ? 2700 : pair.startsWith('SOL') ? 185 : 1;
  return {
    buyBook: {
      exchange: 'Kraken Pro',
      pair,
      timestamp: new Date().toISOString(),
      asks: [
        { price: basePrice * 0.998, amount: 0.85, total: basePrice * 0.998 * 0.85 },
        { price: basePrice * 0.9985, amount: 1.40, total: basePrice * 0.9985 * 1.40 },
        { price: basePrice * 0.999, amount: 2.10, total: basePrice * 0.999 * 2.10 },
        { price: basePrice * 0.9995, amount: 3.50, total: basePrice * 0.9995 * 3.50 },
      ],
      bids: [
        { price: basePrice * 0.9975, amount: 1.10, total: basePrice * 0.9975 * 1.10 },
        { price: basePrice * 0.9970, amount: 2.20, total: basePrice * 0.9970 * 2.20 },
      ],
    },
    sellBook: {
      exchange: 'Binance',
      pair,
      timestamp: new Date().toISOString(),
      bids: [
        { price: basePrice * 1.009, amount: 1.20, total: basePrice * 1.009 * 1.20 },
        { price: basePrice * 1.0085, amount: 2.80, total: basePrice * 1.0085 * 2.80 },
        { price: basePrice * 1.0080, amount: 4.10, total: basePrice * 1.0080 * 4.10 },
        { price: basePrice * 1.0075, amount: 5.50, total: basePrice * 1.0075 * 5.50 },
      ],
      asks: [
        { price: basePrice * 1.0095, amount: 0.90, total: basePrice * 1.0095 * 0.90 },
        { price: basePrice * 1.010, amount: 2.10, total: basePrice * 1.010 * 2.10 },
      ],
    },
  };
}
